/*
 * Copyright (C) 2026 Jason Monk <monkopedia@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:OptIn(UnsafeDuringIrConstructionAPI::class)

package com.monkopedia.ksrpc.plugin

import org.jetbrains.kotlin.GeneratedDeclarationKey
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.backend.js.utils.isDispatchReceiver
import org.jetbrains.kotlin.ir.builders.IrBlockBodyBuilder
import org.jetbrains.kotlin.ir.builders.irCall
import org.jetbrains.kotlin.ir.builders.irCallConstructor
import org.jetbrains.kotlin.ir.builders.irDelegatingConstructorCall
import org.jetbrains.kotlin.ir.builders.irGet
import org.jetbrains.kotlin.ir.builders.irGetObject
import org.jetbrains.kotlin.ir.builders.irInt
import org.jetbrains.kotlin.ir.builders.irReturn
import org.jetbrains.kotlin.ir.builders.irVararg
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrConstructor
import org.jetbrains.kotlin.ir.declarations.IrDeclaration
import org.jetbrains.kotlin.ir.declarations.IrParameterKind
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.IrSimpleFunction
import org.jetbrains.kotlin.ir.declarations.IrValueParameter
import org.jetbrains.kotlin.ir.expressions.IrBody
import org.jetbrains.kotlin.ir.expressions.IrClassReference
import org.jetbrains.kotlin.ir.expressions.IrConstructorCall
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.symbols.IrClassSymbol
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.types.IrSimpleType
import org.jetbrains.kotlin.ir.types.IrType
import org.jetbrains.kotlin.ir.types.classFqName
import org.jetbrains.kotlin.ir.types.defaultType
import org.jetbrains.kotlin.ir.types.typeOrFail
import org.jetbrains.kotlin.ir.types.typeWith
import org.jetbrains.kotlin.ir.util.companionObject
import org.jetbrains.kotlin.ir.util.constructors
import org.jetbrains.kotlin.ir.util.fqNameForIrSerialization
import org.jetbrains.kotlin.ir.util.kotlinFqName
import org.jetbrains.kotlin.ir.util.parentAsClass
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * IR transformer for companion objects generated by [FirSubtypeCompanionGenerator] on
 * plain-Kotlin subtypes of `@KsService` interfaces.
 *
 * For **Scenario 1** (non-generic subtype, e.g. `interface TypedFoo : GenericEcho<String>`):
 * - The companion directly implements `RpcObject<TypedFoo>`.
 * - `serviceName`, `endpoints`, `findEndpoint`, `createStub` all delegate to the parent
 *   service's `RpcObject`, which is obtained by constructing the parent's `Obj` class
 *   with the concrete type arguments baked into the subtype's supertype reference.
 *
 * For **Scenario 2** (generic subtype, e.g. `interface TypedFooT<T> : GenericEcho<T>`):
 * - The companion implements `RpcObjectFactory<TypedFooT<*>>`.
 * - `arity` returns the subtype's own type parameter count.
 * - `create(typeArgs)` maps the subtype's type args through the substitution and delegates
 *   to the parent's factory.
 *
 * See issue #95.
 */
class SubtypeCompanionGeneration(
    context: IrPluginContext,
    private val env: KsrpcGenerationEnvironment
) : AbstractTransformerForGenerator(context) {

    override fun interestedIn(key: GeneratedDeclarationKey?): Boolean =
        key is FirSubtypeCompanionGenerator.Key

    override fun generateChildrenForClass(
        declaration: IrClass,
        key: GeneratedDeclarationKey?
    ): Collection<IrDeclaration> {
        val k = key as FirSubtypeCompanionGenerator.Key
        val subtypeClass = declaration.parentAsClass

        // Emit @RpcObjectKey pointing at this companion on the subtype class.
        env.rpcObjectKey?.let { rpcObjectKeySymbol ->
            val objectReference = createClassReference(context, declaration)
            subtypeClass.annotations += createRpcObjectAnnotation(
                subtypeClass,
                rpcObjectKeySymbol,
                objectReference
            )
        }

        declaration.isCompanion = true

        // Both generic and non-generic subtypes use RpcObjectFactory with arity property.
        val arity = subtypeClass.typeParameters.size
        declaration.declarations
            .filterIsInstance<IrProperty>()
            .firstOrNull { it.name == FqConstants.ARITY }
            ?.let { property ->
                property.getter?.body = context.irBuilder(property.getter!!).irSynthBody {
                    +irReturn(irInt(arity))
                }
            }

        return emptyList()
    }

    private fun createRpcObjectAnnotation(
        irClass: IrClass,
        rpcObjectKey: IrClassSymbol,
        objectReference: IrClassReference
    ): IrConstructorCall {
        val primaryConstructor = rpcObjectKey.constructors.find { it.owner.isPrimary }
            ?: reportInternal(
                "RpcObjectKey has no primary constructor — ksrpc-core runtime must " +
                    "match the compiler plugin"
            )
        return context.irBuilder(irClass).irCallConstructor(primaryConstructor, emptyList())
            .apply { putArgs(objectReference) }
    }

    override fun generateBodyForFunction(
        function: IrSimpleFunction,
        key: GeneratedDeclarationKey?
    ): IrBody? {
        val k = key as FirSubtypeCompanionGenerator.Key
        val companionClass = function.parentAsClass
        val subtypeClass = companionClass.parentAsClass

        // Handle property getters
        function.correspondingPropertySymbol?.owner?.name?.let { propertyName ->
            if (propertyName == FqConstants.ARITY) {
                return context.irBuilder(function).irSynthBody {
                    +irReturn(irInt(subtypeClass.typeParameters.size))
                }
            }
        }

        return when (function.name) {
            FqConstants.CREATE -> generateCreateBody(function, k, subtypeClass)
            else -> null
        }
    }

    /**
     * Generate body for `create(typeArgs: List<KType>): RpcObject<...>`.
     *
     * - **Non-generic subtype** (e.g. `interface TypedFoo : GenericEcho<String>`):
     *   Ignores `typeArgs` (arity is 0), constructs the parent's `Obj<String>(serializer<String>())`
     *   directly, returning it as the `RpcObject`. This avoids the JVM bridge-method
     *   ClassCastException that would occur if the companion's `createStub` tried to return the
     *   parent's Stub as the subtype (see issue #136).
     *
     * - **Generic subtype** (e.g. `interface TypedFooT<T> : GenericEcho<T>`):
     *   Maps `typeArgs` through the subtype-to-parent type-arg substitution and delegates
     *   to the parent's `create(mappedTypeArgs)`.
     */
    private fun generateCreateBody(
        function: IrSimpleFunction,
        key: FirSubtypeCompanionGenerator.Key,
        subtypeClass: IrClass
    ): IrBody {
        val parentServiceClass = findIrClass(key.parentServiceClassId)
            ?: reportInternal(
                "Can't find parent service ${key.parentServiceClassId} for subtype " +
                    "${subtypeClass.kotlinFqName.asString()}"
            )

        if (!key.isGeneric) {
            // Non-generic subtype: construct the parent's RpcObject directly with baked-in
            // type args from the subtype's supertype reference.
            return context.irBuilder(function).irSynthBody {
                val rpcObj = buildParentRpcObjectExpr(this, subtypeClass, parentServiceClass)
                +irReturn(rpcObj)
            }
        }

        // Generic subtype: delegate to parent's factory with mapped type args.
        val parentCompanion = parentServiceClass.companionObject()
            ?: reportInternal(
                "Parent service ${parentServiceClass.kotlinFqName.asString()} has no companion"
            )

        val parentCreateMethod = parentCompanion.declarations
            .filterIsInstance<IrSimpleFunction>()
            .firstOrNull { it.name == FqConstants.CREATE }
            ?: reportInternal(
                "Parent companion has no create method"
            )

        return context.irBuilder(function).irSynthBody {
            val typeArgsParam = function.parameters.first { !it.isDispatchReceiver }

            // Compute subtype->parent type arg mapping
            val mapping = computeSubtypeToParentTypeArgMapping(subtypeClass, parentServiceClass)

            val mappedTypeArgs = if (mapping != null) {
                buildMappedTypeArgsList(this, typeArgsParam, mapping)
            } else {
                // Direct pass-through
                irGet(typeArgsParam)
            }

            +irReturn(
                irCall(parentCreateMethod).apply {
                    dispatchReceiver = irGetObject(parentCompanion.symbol)
                    arguments[1] = mappedTypeArgs
                }
            )
        }
    }

    /**
     * Build an expression that creates a mapped List<KType> from the input typeArgs.
     * Each entry selects typeArgs[mapping[i]].
     */
    private fun buildMappedTypeArgsList(
        builder: IrBlockBodyBuilder,
        typeArgsParam: IrValueParameter,
        mapping: List<Int>
    ): IrExpression = with(builder) {
        val listClass = context.irBuiltIns.listClass
        val listGet = listClass.owner.declarations
            .filterIsInstance<IrSimpleFunction>()
            .first { it.name.asString() == "get" && it.parameters.size == 2 }
        val ktypeSymbol = this@SubtypeCompanionGeneration.context.referenceClass(FqConstants.KTYPE)
            ?: reportInternal("Can't resolve KType")
        val ktypeType = ktypeSymbol.defaultType
        val elements = mapping.map { idx ->
            irCall(listGet).apply {
                dispatchReceiver = irGet(typeArgsParam)
                arguments[1] = irInt(idx)
            }
        }
        irCall(env.listOfFunction).apply {
            typeArguments[0] = ktypeType
            val varargParameter = env.listOfFunction.owner.parameters
                .single { it.kind == IrParameterKind.Regular }
            arguments[varargParameter] = irVararg(ktypeType, elements)
        }
    }

    /**
     * Compute the mapping from parent service type parameters to subtype type parameters.
     *
     * For `interface Sub<A, B> : Parent<B, A>`:
     *   Parent has type params [P0, P1]
     *   Sub has type params [A=0, B=1]
     *   The supertype ref is Parent<B, A> -> mapping is [1, 0]
     *
     * Returns null if it's a direct 1:1 pass-through (optimization).
     */
    private fun computeSubtypeToParentTypeArgMapping(
        subtypeClass: IrClass,
        parentServiceClass: IrClass
    ): List<Int>? {
        val parentFqName = parentServiceClass.fqNameForIrSerialization
        val parentSupertype = subtypeClass.superTypes
            .filterIsInstance<IrSimpleType>()
            .firstOrNull { it.classFqName == parentFqName }
            ?: return null

        val parentTypeArgs = parentSupertype.arguments
        if (parentTypeArgs.isEmpty()) return null

        val subtypeTypeParams = subtypeClass.typeParameters
        val mapping = parentTypeArgs.map { arg ->
            val argType = arg.typeOrFail
            val classifier = (argType as? IrSimpleType)?.classifier
            if (classifier is org.jetbrains.kotlin.ir.symbols.IrTypeParameterSymbol) {
                subtypeTypeParams.indexOfFirst { it.symbol == classifier }
            } else {
                -1
            }
        }

        val isPassthrough = mapping.withIndex().all { (i, v) -> v == i }
        return if (isPassthrough) null else mapping
    }

    /**
     * Build an IR expression that evaluates to the parent's `RpcObject` for the subtype's
     * concrete type arguments. For a non-generic parent, this is just `irGetObject(companion)`.
     * For a generic parent with concrete type args baked in the subtype declaration
     * (Scenario 1), this constructs the parent's `Obj<T, ...>` with serializer args.
     */
    private fun buildParentRpcObjectExpr(
        builder: IrBlockBodyBuilder,
        subtypeClass: IrClass,
        parentServiceClass: IrClass
    ): IrExpression = with(builder) {
        val parentCompanion = parentServiceClass.companionObject()
            ?: reportInternal(
                "Parent service ${parentServiceClass.kotlinFqName.asString()} has no companion"
            )

        if (parentServiceClass.typeParameters.isEmpty()) {
            return irGetObject(parentCompanion.symbol)
        }

        // Generic parent — find the concrete type args from the supertype reference.
        val parentFqName = parentServiceClass.fqNameForIrSerialization
        val parentSupertype = subtypeClass.superTypes
            .filterIsInstance<IrSimpleType>()
            .firstOrNull { it.classFqName == parentFqName }
            ?: reportInternal(
                "Can't find supertype reference to ${parentServiceClass.kotlinFqName.asString()} " +
                    "on ${subtypeClass.kotlinFqName.asString()}"
            )

        val objClass = parentServiceClass.declarations
            .filterIsInstance<IrClass>()
            .firstOrNull { it.name == FqConstants.OBJ }
            ?: reportInternal(
                "Parent service ${parentServiceClass.kotlinFqName.asString()} has no Obj class"
            )

        val objConstructor = objClass.constructors.first { it.isPrimary }
        val typeArgs = parentSupertype.arguments.map { it.typeOrFail }

        val serializerFn = env.serializerMethod
            ?: reportInternal(
                "can't resolve kotlinx.serialization.serializer<T>() — " +
                    "kotlinx-serialization-core must be on the compile classpath"
            )

        val serializerArgs = typeArgs.map { typeArg ->
            irCall(serializerFn).apply {
                typeArguments[0] = typeArg
                this.type = env.kSerializer.typeWith(typeArg)
            }
        }

        return irCallConstructor(objConstructor.symbol, typeArgs).apply {
            type = objClass.typeWith(typeArgs)
            putArgs(*serializerArgs.toTypedArray())
        }
    }

    private fun findIrClass(classId: ClassId): IrClass? =
        context.referenceClass(classId)?.owner

    override fun generateBodyForConstructor(
        constructor: IrConstructor,
        key: GeneratedDeclarationKey?
    ): IrBody = context.irBuilder(constructor).irSynthBody {
        +irDelegatingConstructorCall(
            context.irBuiltIns.anyClass.owner.constructors.single()
        )
    }
}
