/*
 * Copyright (C) 2026 Jason Monk <monkopedia@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.monkopedia.ksrpc.annotation

/**
 * Annotation tagging an interface for processing by the compiler plugin.
 *
 * interfaces tagged with this are expected to extend [com.monkopedia.ksrpc.RpcService], and will
 * have a companion generated for them that implements [com.monkopedia.ksrpc.RpcObject] for itself.
 */
annotation class KsService

/**
 * Tags a method within a [KsService] for rpc calls.
 *
 * The [name] must be unique within a [KsService] but need not be unique
 * globally.
 */
annotation class KsMethod(val name: String)

/**
 * Meta-annotation that marks an annotation class as a sibling of [KsMethod] whose
 * arguments should be captured by the ksrpc compiler plugin and propagated into
 * the generated `RpcMethod` descriptor.
 *
 * Apply this to an annotation class to opt it in to compiler-driven metadata
 * propagation. Only annotations applied to functions also annotated with
 * [KsMethod] are captured. The arguments of qualifying annotations are stored
 * as `MethodMetadata` on the generated `RpcMethod`, where transport layers can
 * read them at serialize time.
 *
 * The annotation arguments must be of supported metadata-value types:
 * primitives (String, Int, Long, Boolean, Double, Float), KClass references,
 * enum values, or arrays/lists thereof. Nested annotation values are not
 * supported.
 *
 * For forward compatibility, an older version of ksrpc reading a descriptor
 * generated by a newer version sees unknown sibling annotations as opaque
 * `MethodMetadata` entries — they remain queryable by FQ name without
 * requiring the unknown annotation class on the classpath.
 */
@Target(AnnotationTarget.ANNOTATION_CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class KsMethodMetadata
