/*
 * Copyright (C) 2026 Jason Monk <monkopedia@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.monkopedia.ksrpc.annotation

/**
 * Marks ksrpc symbols that exist solely to support the library's own
 * implementation — including code generated by the compiler plugin and
 * bridges between modules. These symbols are public for technical reasons
 * but are not part of the supported API surface and may change at any time.
 *
 * Callers must opt in explicitly, either by annotating the use site with
 * `@OptIn(KsrpcInternal::class)` or by propagating the requirement with
 * `@KsrpcInternal` themselves.
 */
@RequiresOptIn(
    message = "This ksrpc symbol is internal to the library and may change without notice"
)
@Retention(AnnotationRetention.BINARY)
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY,
    AnnotationTarget.TYPEALIAS,
    AnnotationTarget.CONSTRUCTOR,
    AnnotationTarget.PROPERTY_GETTER,
    AnnotationTarget.PROPERTY_SETTER
)
annotation class KsrpcInternal
